In [106]:
import pandas as pd

In [107]:
import numpy as np

In [108]:
import re

In [109]:
df=pd.read_csv("messy_employee_data.csv")

In [110]:
df

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Joining_Date,Phone_Number,Email,Monthly_Bonus,Salary_Text
0,EMP0001,Rahul Sharma,28.0,Male,Mumbai,Sales,94163.0,16.0,Graduate,1.0,15/03/2020,9876543210,rahul@gmail.com,6320.0,Rs. 94163.0/-
1,EMP0002,Priya Patel,41.0,Female,Pune,IT,50939.0,7.0,Post Graduate,8.0,2019-07-22,8765432109,priya@yahoo.com,14216.0,50939
2,EMP0003,Amit Kumar,36.0,male,Delhi,HR,73925.0,3.0,graduate,5.0,01-01-2021,+91-9876543210,amit.kumar,3779.0,73925
3,EMP0004,Sneha Joshi,32.0,FEMALE,Bangalore,Marketing,67941.0,5.0,POST GRADUATE,4.0,March 2022,(987) 654-3210,sneha@,18308.0,67941
4,EMP0005,Vikram Singh,29.0,M,mumbai,sales,46834.0,7.0,Diploma,8.0,22.04.2018,98765,vikram@company.com,2581.0,Rs. 46834.0/-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,Rahul Sharma,NaN,F,PUNE,it,NaN,NaN,POST GRADUATE,NaN,2020/11/30,(987) 654-3210,sneha@,NaN,NaN
196,NaN,Priya Patel,NaN,female,delhi,H.R,NaN,NaN,Diploma,NaN,15-Aug-2019,98765,vikram@company.com,NaN,NaN
197,NaN,Amit Kumar,NaN,Male,bangalore,marketing,NaN,NaN,diploma,NaN,2021-13-45,1234567890123,pooja gmail.com,NaN,NaN
198,NaN,Sneha Joshi,NaN,Female,Hyderabad,Finance,NaN,NaN,12th,NaN,NaN,ABCDEFGHIJ,NaN,NaN,NaN
199,NaN,Vikram Singh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neha@valid.com,NaN,NaN

In [111]:
df.shape

(200, 15)

In [112]:
df.head(10)

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Joining_Date,Phone_Number,Email,Monthly_Bonus,Salary_Text
0,EMP0001,Rahul Sharma,28.0,Male,Mumbai,Sales,94163.0,16.0,Graduate,1.0,15/03/2020,9876543210,rahul@gmail.com,6320.0,Rs. 94163.0/-
1,EMP0002,Priya Patel,41.0,Female,Pune,IT,50939.0,7.0,Post Graduate,8.0,2019-07-22,8765432109,priya@yahoo.com,14216.0,50939
2,EMP0003,Amit Kumar,36.0,male,Delhi,HR,73925.0,3.0,graduate,5.0,01-01-2021,+91-9876543210,amit.kumar,3779.0,73925
3,EMP0004,Sneha Joshi,32.0,FEMALE,Bangalore,Marketing,67941.0,5.0,POST GRADUATE,4.0,March 2022,(987) 654-3210,sneha@,18308.0,67941
4,EMP0005,Vikram Singh,29.0,M,mumbai,sales,46834.0,7.0,Diploma,8.0,22.04.2018,98765,vikram@company.com,2581.0,Rs. 46834.0/-
5,EMP0006,Pooja Mehta,42.0,F,PUNE,it,43047.0,19.0,diploma,7.0,2020/11/30,1234567890123,pooja gmail.com,13677.0,Rs. 43047.0/-
6,EMP0007,Rohan Kulkarni,28.0,female,delhi,H.R,51105.0,2.0,12th,2.0,15-Aug-2019,ABCDEFGHIJ,NaN,6713.0,Rs. 51105.0/-
7,EMP0008,Neha Verma,40.0,Male,bangalore,marketing,100766.0,15.0,NaN,1.0,2021-13-45,NaN,neha@valid.com,17639.0,100766
8,EMP0009,Suresh Nair,44.0,Female,Hyderabad,Finance,40707.0,2.0,Graduate,4.0,NaN,9876543210,rahul@gmail.com,5804.0,40707
9,EMP0010,Kavita Reddy,32.0,NaN,NaN,NaN,46976.0,17.0,Post Graduate,8.0,NaN,8765432109,priya@yahoo.com,19222.0,46976

In [113]:
df.tail(10)

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Joining_Date,Phone_Number,Email,Monthly_Bonus,Salary_Text
190,NaN,rahul sharma,NaN,Male,Mumbai,Sales,NaN,NaN,12th,NaN,15/03/2020,ABCDEFGHIJ,NaN,NaN,NaN
191,NaN,PRIYA PATEL,NaN,Female,Pune,IT,NaN,NaN,NaN,NaN,2019-07-22,NaN,neha@valid.com,NaN,NaN
192,NaN,Amit Kumar,NaN,male,Delhi,HR,NaN,NaN,Graduate,NaN,01-01-2021,9876543210,rahul@gmail.com,NaN,NaN
193,NaN,Sneha Joshi,NaN,FEMALE,Bangalore,Marketing,NaN,NaN,Post Graduate,NaN,March 2022,8765432109,priya@yahoo.com,NaN,NaN
194,NaN,NaN,NaN,M,mumbai,sales,NaN,NaN,graduate,NaN,22.04.2018,+91-9876543210,amit.kumar,NaN,NaN
195,NaN,Rahul Sharma,NaN,F,PUNE,it,NaN,NaN,POST GRADUATE,NaN,2020/11/30,(987) 654-3210,sneha@,NaN,NaN
196,NaN,Priya Patel,NaN,female,delhi,H.R,NaN,NaN,Diploma,NaN,15-Aug-2019,98765,vikram@company.com,NaN,NaN
197,NaN,Amit Kumar,NaN,Male,bangalore,marketing,NaN,NaN,diploma,NaN,2021-13-45,1234567890123,pooja gmail.com,NaN,NaN
198,NaN,Sneha Joshi,NaN,Female,Hyderabad,Finance,NaN,NaN,12th,NaN,NaN,ABCDEFGHIJ,NaN,NaN,NaN
199,NaN,Vikram Singh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neha@valid.com,NaN,NaN

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        185 non-null    object
 1   Employee_Name      187 non-null    object
 2   Age                166 non-null    float64
 3   Gender             180 non-null    object
 4   City               180 non-null    object
 5   Department         180 non-null    object
 6   Salary             165 non-null    float64
 7   Experience_Years   169 non-null    float64
 8   Education          175 non-null    object
 9   Performance_Score  170 non-null    float64
 10  Joining_Date       160 non-null    object
 11  Phone_Number       175 non-null    object
 12  Email              175 non-null    object
 13  Monthly_Bonus      170 non-null    float64
 14  Salary_Text        165 non-null    object
dtypes: float64(5), object(10)
memory usage: 23.6+ KB

In [115]:
df.isnull()

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Joining_Date,Phone_Number,Email,Monthly_Bonus,Salary_Text
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,True,False,True,False,False,False,True,True,False,True,False,False,False,True,True
196,True,False,True,False,False,False,True,True,False,True,False,False,False,True,True
197,True,False,True,False,False,False,True,True,False,True,False,False,False,True,True
198,True,False,True,False,False,False,True,True,False,True,True,False,True,True,True
199,True,False,True,True,True,True,True,True,True,True,True,True,False,True,True

In [116]:
df.isnull().sum()

Employee_ID          15
Employee_Name        13
Age                  34
Gender               20
City                 20
Department           20
Salary               35
Experience_Years     31
Education            25
Performance_Score    30
Joining_Date         40
Phone_Number         25
Email                25
Monthly_Bonus        30
Salary_Text          35
dtype: int64

In [117]:
df.describe()

,Age,Salary,Experience_Years,Performance_Score,Monthly_Bonus
count,166.000000,165.000000,169.000000,170.000000,170.000000
mean,39.433735,89418.448485,9.798817,5.535294,10762.111765
std,77.008570,81011.105842,9.912462,7.812253,5264.667796
min,-5.000000,-5000.000000,-5.000000,-1.000000,1009.000000
25%,27.000000,50939.000000,3.000000,3.000000,6260.000000
50%,32.500000,85713.000000,9.000000,5.000000,10885.500000
75%,38.000000,118264.000000,15.000000,7.000000,15164.500000
max,999.000000,999999.000000,100.000000,100.000000,19977.000000

In [118]:
df.dtypes

Employee_ID           object
Employee_Name         object
Age                  float64
Gender                object
City                  object
Department            object
Salary               float64
Experience_Years     float64
Education             object
Performance_Score    float64
Joining_Date          object
Phone_Number          object
Email                 object
Monthly_Bonus        float64
Salary_Text           object
dtype: object

In [119]:
(df.isnull().sum()/len(df))*100

Employee_ID           7.5
Employee_Name         6.5
Age                  17.0
Gender               10.0
City                 10.0
Department           10.0
Salary               17.5
Experience_Years     15.5
Education            12.5
Performance_Score    15.0
Joining_Date         20.0
Phone_Number         12.5
Email                12.5
Monthly_Bonus        15.0
Salary_Text          17.5
dtype: float64

In [120]:
df.duplicated().sum()

np.int64(0)

In [121]:
df[df.duplicated()]

Empty DataFrame
Columns: [Employee_ID, Employee_Name, Age, Gender, City, Department, Salary, Experience_Years, Education, Performance_Score, Joining_Date, Phone_Number, Email, Monthly_Bonus, Salary_Text]
Index: []

In [122]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Age', 'Gender', 'City', 'Department',
       'Salary', 'Experience_Years', 'Education', 'Performance_Score',
       'Joining_Date', 'Phone_Number', 'Email', 'Monthly_Bonus',
       'Salary_Text'],
      dtype='object')

In [123]:
df['Gender'].unique()

array(['Male', 'Female', 'male', 'FEMALE', 'M', 'F', 'female', 'Male ',
       ' Female', nan], dtype=object)

In [124]:
df['Education'].unique()

array(['Graduate', 'Post Graduate', 'graduate', 'POST GRADUATE',
       'Diploma', 'diploma', '12th', nan], dtype=object)

In [125]:
df['Department'].unique()

array(['Sales', 'IT', 'HR', 'Marketing', 'sales', 'it', 'H.R',
       'marketing', 'Finance', nan], dtype=object)

In [126]:
df['City'].unique()

array(['Mumbai', 'Pune', 'Delhi', 'Bangalore', 'mumbai', 'PUNE', 'delhi',
       'bangalore', 'Hyderabad', nan], dtype=object)

In [127]:
df['Gender'].value_counts()

Gender
Male       20
Female     20
male       20
FEMALE     20
M          20
F          20
female     20
Male       20
 Female    20
Name: count, dtype: int64

In [128]:
df['City'].value_counts()

City
Mumbai       20
Pune         20
Delhi        20
Bangalore    20
mumbai       20
PUNE         20
delhi        20
bangalore    20
Hyderabad    20
Name: count, dtype: int64

In [129]:
df=df.drop_duplicates(subset='Employee_ID',keep='first')

In [130]:
df=df.reset_index(drop=True)

In [131]:
df

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Joining_Date,Phone_Number,Email,Monthly_Bonus,Salary_Text
0,EMP0001,Rahul Sharma,28.0,Male,Mumbai,Sales,94163.0,16.0,Graduate,1.0,15/03/2020,9876543210,rahul@gmail.com,6320.0,Rs. 94163.0/-
1,EMP0002,Priya Patel,41.0,Female,Pune,IT,50939.0,7.0,Post Graduate,8.0,2019-07-22,8765432109,priya@yahoo.com,14216.0,50939
2,EMP0003,Amit Kumar,36.0,male,Delhi,HR,73925.0,3.0,graduate,5.0,01-01-2021,+91-9876543210,amit.kumar,3779.0,73925
3,EMP0004,Sneha Joshi,32.0,FEMALE,Bangalore,Marketing,67941.0,5.0,POST GRADUATE,4.0,March 2022,(987) 654-3210,sneha@,18308.0,67941
4,EMP0005,Vikram Singh,29.0,M,mumbai,sales,46834.0,7.0,Diploma,8.0,22.04.2018,98765,vikram@company.com,2581.0,Rs. 46834.0/-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,EMP0167,Priya Patel,NaN,female,delhi,H.R,NaN,-5.0,12th,-1.0,15-Aug-2019,ABCDEFGHIJ,NaN,18680.0,NaN
167,EMP0168,Amit Kumar,NaN,Male,bangalore,marketing,NaN,50.0,NaN,11.0,2021-13-45,NaN,neha@valid.com,7229.0,NaN
168,EMP0169,Sneha Joshi,NaN,Female,Hyderabad,Finance,NaN,100.0,Graduate,15.0,NaN,9876543210,rahul@gmail.com,17509.0,NaN
169,EMP0170,Vikram Singh,NaN,NaN,NaN,NaN,NaN,NaN,Post Graduate,100.0,NaN,8765432109,priya@yahoo.com,16147.0,NaN
170,NaN,Pooja Mehta,NaN,F,PUNE,it,NaN,NaN,Post Graduate,NaN,2020/11/30,8765432109,priya@yahoo.com,NaN,NaN

In [132]:
df['Employee_Name']=df['Employee_Name'].str.strip()

In [133]:
df['Employee_Name']

0      Rahul Sharma
1       Priya Patel
2        Amit Kumar
3       Sneha Joshi
4      Vikram Singh
           ...
166     Priya Patel
167      Amit Kumar
168     Sneha Joshi
169    Vikram Singh
170     Pooja Mehta
Name: Employee_Name, Length: 171, dtype: object

In [134]:
df.loc[1,'Employee_Name'] = ' Priya   Patel          '

In [135]:
df['Employee_Name']

0                  Rahul Sharma
1       Priya   Patel
2                    Amit Kumar
3                   Sneha Joshi
4                  Vikram Singh
                 ...
166                 Priya Patel
167                  Amit Kumar
168                 Sneha Joshi
169                Vikram Singh
170                 Pooja Mehta
Name: Employee_Name, Length: 171, dtype: object

In [136]:
df['Employee_Name']=df['Employee_Name'].str.strip()

In [137]:
df['Gender'].str.strip()
df['City'].str.strip()
df['Education'].str.strip()
df['Department'].str.strip()

0          Sales
1             IT
2             HR
3      Marketing
4          sales
         ...
166          H.R
167    marketing
168      Finance
169          NaN
170           it
Name: Department, Length: 171, dtype: object

In [138]:
df['Employee_Name']=df['Employee_Name'].str.replace(r'\s+',' ',regex=True)

In [139]:
df['Employee_Name']

0      Rahul Sharma
1       Priya Patel
2        Amit Kumar
3       Sneha Joshi
4      Vikram Singh
           ...
166     Priya Patel
167      Amit Kumar
168     Sneha Joshi
169    Vikram Singh
170     Pooja Mehta
Name: Employee_Name, Length: 171, dtype: object

In [140]:
df['Gender']=df['Gender'].str.strip().str.title()

In [141]:
df['Gender']

0        Male
1      Female
2        Male
3      Female
4           M
        ...
166    Female
167      Male
168    Female
169       NaN
170         F
Name: Gender, Length: 171, dtype: object

In [142]:
df['Gender']=df['Gender'].replace(
    {
        'F':'Female',
        'M':'Male'
    }
)

In [143]:
df['Gender']

0        Male
1      Female
2        Male
3      Female
4        Male
        ...
166    Female
167      Male
168    Female
169       NaN
170    Female
Name: Gender, Length: 171, dtype: object

In [144]:
df['Gender'].isnull().sum()

np.int64(17)

In [145]:
df['City']=df['City'].str.title()

In [146]:
df['City']

0         Mumbai
1           Pune
2          Delhi
3      Bangalore
4         Mumbai
         ...
166        Delhi
167    Bangalore
168    Hyderabad
169          NaN
170         Pune
Name: City, Length: 171, dtype: object

In [147]:
df['City'].value_counts()

City
Pune         35
Mumbai       34
Delhi        34
Bangalore    34
Hyderabad    17
Name: count, dtype: int64

In [148]:
df['Department']=df['Department'].str.title()

In [149]:
df['Department'].value_counts()

Department
It           35
Sales        34
Marketing    34
Hr           17
H.R          17
Finance      17
Name: count, dtype: int64

In [150]:
df['Department']=df['Department'].replace(
    {
        'Hr':'HR',
        'H.R':'HR',
        'It':'IT'
    }
)

In [151]:
df['Department']

0          Sales
1             IT
2             HR
3      Marketing
4          Sales
         ...
166           HR
167    Marketing
168      Finance
169          NaN
170           IT
Name: Department, Length: 171, dtype: object

In [152]:
df['Department'].value_counts()

Department
IT           35
Sales        34
HR           34
Marketing    34
Finance      17
Name: count, dtype: int64

In [153]:
df['Education'].value_counts()

Education
Post Graduate    23
Graduate         22
graduate         21
POST GRADUATE    21
Diploma          21
diploma          21
12th             21
Name: count, dtype: int64

In [154]:
df['Education']=df['Education'].str.title()

In [155]:
df['Education'].value_counts()

Education
Post Graduate    44
Graduate         43
Diploma          42
12Th             21
Name: count, dtype: int64

In [156]:
df['Age']=df['Age'].astype(float)
df['Age']=np.where(((df['Age'] < 18) | (df['Age'] > 65)),np.nan,df['Age'])

In [157]:
df['Age']

0      28.0
1      41.0
2      36.0
3      32.0
4      29.0
       ...
166     NaN
167     NaN
168     NaN
169     NaN
170     NaN
Name: Age, Length: 171, dtype: float64

In [158]:
df['Age'].isnull().sum()

np.int64(11)

In [161]:
df['Salary']=df['Salary'].astype(float)
df['Salary']=np.where(((df['Salary']<0)|(df['Salary']>50000)),np.nan,df['Salary'])

In [162]:
df['Salary']

0          NaN
1          NaN
2          NaN
3          NaN
4      46834.0
        ...
166        NaN
167        NaN
168        NaN
169        NaN
170        NaN
Name: Salary, Length: 171, dtype: float64

In [164]:
(df['Salary'].isnull().sum()/len(df))*100

np.float64(78.94736842105263)

In [165]:
df['Experience_Years']=df['Experience_Years'].astype(float)
df['Experience_Years']=np.where(((df['Experience_Years']<0)|(df['Experience_Years']>40)),np.nan,df['Experience_Years'])

In [166]:
df['Experience_Years']

0      16.0
1       7.0
2       3.0
3       5.0
4       7.0
       ...
166     NaN
167     NaN
168     NaN
169     NaN
170     NaN
Name: Experience_Years, Length: 171, dtype: float64

In [167]:
(df['Experience_Years'].isnull().sum()/len(df))*100

np.float64(3.508771929824561)

In [168]:
df['Performance_Score']=df['Performance_Score'].astype(float)
df['Performance_Score']=np.where(((df['Performance_Score']<0)|(df['Performance_Score']>10)),np.nan,df['Performance_Score'])

In [169]:
(df['Performance_Score'].isnull().sum()/len(df))*100

np.float64(2.923976608187134)

In [170]:
print(df[['Salary','Age','Experience_Years','Performance_Score']].isnull().sum())

Salary               135
Age                   11
Experience_Years       6
Performance_Score      5
dtype: int64

In [176]:
#filling categorical values by median of the same column
df['Age']=df['Age'].fillna(df['Age'].median())
df['Experience_Years']=df['Experience_Years'].fillna(df['Experience_Years'].median())
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df['Performance_Score']=df['Performance_Score'].fillna(df['Performance_Score'].median())

In [177]:
print(df[['Salary','Age','Experience_Years','Performance_Score']].isnull().sum())

Salary               0
Age                  0
Experience_Years     0
Performance_Score    0
dtype: int64

In [178]:
df['Salary']

0      36797.0
1      36797.0
2      36797.0
3      36797.0
4      46834.0
        ...
166    36797.0
167    36797.0
168    36797.0
169    36797.0
170    36797.0
Name: Salary, Length: 171, dtype: float64

In [179]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [180]:
df['Education']=df['Education'].fillna(df['Education'].mode()[0])
df['City']=df['City'].fillna(df['City'].mode()[0])
df['Department']=df['Department'].fillna(df['Department'].mode()[0])

In [181]:
df[['Gender','City','Department',"Education"]].isnull().sum()

Gender        0
City          0
Department    0
Education     0
dtype: int64

In [182]:
df['Gender']

0        Male
1      Female
2        Male
3      Female
4        Male
        ...
166    Female
167      Male
168    Female
169    Female
170    Female
Name: Gender, Length: 171, dtype: object

In [184]:
df=df.dropna(subset=['Employee_Name','Employee_ID'])

In [185]:
df=df.reset_index(drop=True)

In [186]:
df

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Joining_Date,Phone_Number,Email,Monthly_Bonus,Salary_Text
0,EMP0001,Rahul Sharma,28.0,Male,Mumbai,Sales,36797.0,16.0,Graduate,1.0,15/03/2020,9876543210,rahul@gmail.com,6320.0,Rs. 94163.0/-
1,EMP0002,Priya Patel,41.0,Female,Pune,IT,36797.0,7.0,Post Graduate,8.0,2019-07-22,8765432109,priya@yahoo.com,14216.0,50939
2,EMP0003,Amit Kumar,36.0,Male,Delhi,HR,36797.0,3.0,Graduate,5.0,01-01-2021,+91-9876543210,amit.kumar,3779.0,73925
3,EMP0004,Sneha Joshi,32.0,Female,Bangalore,Marketing,36797.0,5.0,Post Graduate,4.0,March 2022,(987) 654-3210,sneha@,18308.0,67941
4,EMP0005,Vikram Singh,29.0,Male,Mumbai,Sales,46834.0,7.0,Diploma,8.0,22.04.2018,98765,vikram@company.com,2581.0,Rs. 46834.0/-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,EMP0166,Rahul Sharma,32.5,Female,Pune,IT,36797.0,9.0,Diploma,0.0,2020/11/30,1234567890123,pooja gmail.com,19360.0,NaN
155,EMP0167,Priya Patel,32.5,Female,Delhi,HR,36797.0,9.0,12Th,5.0,15-Aug-2019,ABCDEFGHIJ,NaN,18680.0,NaN
156,EMP0168,Amit Kumar,32.5,Male,Bangalore,Marketing,36797.0,9.0,Post Graduate,5.0,2021-13-45,NaN,neha@valid.com,7229.0,NaN
157,EMP0169,Sneha Joshi,32.5,Female,Hyderabad,Finance,36797.0,9.0,Graduate,5.0,NaN,9876543210,rahul@gmail.com,17509.0,NaN
158,EMP0170,Vikram Singh,32.5,Female,Pune,IT,36797.0,9.0,Post Graduate,5.0,NaN,8765432109,priya@yahoo.com,16147.0,NaN

In [187]:
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Age                   0
Gender                0
City                  0
Department            0
Salary                0
Experience_Years      0
Education             0
Performance_Score     0
Joining_Date         29
Phone_Number         20
Email                19
Monthly_Bonus         0
Salary_Text           5
dtype: int64

In [195]:
df

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Phone_Number,Email,Monthly_Bonus
0,EMP0001,Rahul Sharma,28.0,Male,Mumbai,Sales,36797.0,16.0,Graduate,1.0,9876543210,rahul@gmail.com,6320.0
1,EMP0002,Priya Patel,41.0,Female,Pune,IT,36797.0,7.0,Post Graduate,8.0,8765432109,priya@yahoo.com,14216.0
2,EMP0003,Amit Kumar,36.0,Male,Delhi,HR,36797.0,3.0,Graduate,5.0,+91-9876543210,amit.kumar,3779.0
3,EMP0004,Sneha Joshi,32.0,Female,Bangalore,Marketing,36797.0,5.0,Post Graduate,4.0,(987) 654-3210,sneha@,18308.0
4,EMP0005,Vikram Singh,29.0,Male,Mumbai,Sales,46834.0,7.0,Diploma,8.0,98765,vikram@company.com,2581.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,EMP0166,Rahul Sharma,32.5,Female,Pune,IT,36797.0,9.0,Diploma,0.0,1234567890123,pooja gmail.com,19360.0
155,EMP0167,Priya Patel,32.5,Female,Delhi,HR,36797.0,9.0,12Th,5.0,ABCDEFGHIJ,NaN,18680.0
156,EMP0168,Amit Kumar,32.5,Male,Bangalore,Marketing,36797.0,9.0,Post Graduate,5.0,NaN,neha@valid.com,7229.0
157,EMP0169,Sneha Joshi,32.5,Female,Hyderabad,Finance,36797.0,9.0,Graduate,5.0,9876543210,rahul@gmail.com,17509.0
158,EMP0170,Vikram Singh,32.5,Female,Pune,IT,36797.0,9.0,Post Graduate,5.0,8765432109,priya@yahoo.com,16147.0

In [196]:
df['Salary']=df['Salary'].astype(int)
df['Age']=df['Age'].astype(int)
df['Performance_Score']=df['Performance_Score'].astype(int)
df['Experience_Years']=df['Experience_Years'].astype(int)

In [197]:
df['valid_phone']=df['Phone_Number'].apply(
    lambda x:'Valid' if pd.notnull(x) and str(x).isdigit() and len(str(x)) == 10 else 'Invalid'
)

In [198]:
df['valid_phone']

0        Valid
1        Valid
2      Invalid
3      Invalid
4      Invalid
        ...
154    Invalid
155    Invalid
156    Invalid
157      Valid
158      Valid
Name: valid_phone, Length: 159, dtype: object

In [199]:
df

,Employee_ID,Employee_Name,Age,Gender,City,Department,Salary,Experience_Years,Education,Performance_Score,Phone_Number,Email,Monthly_Bonus,valid_phone
0,EMP0001,Rahul Sharma,28,Male,Mumbai,Sales,36797,16,Graduate,1,9876543210,rahul@gmail.com,6320.0,Valid
1,EMP0002,Priya Patel,41,Female,Pune,IT,36797,7,Post Graduate,8,8765432109,priya@yahoo.com,14216.0,Valid
2,EMP0003,Amit Kumar,36,Male,Delhi,HR,36797,3,Graduate,5,+91-9876543210,amit.kumar,3779.0,Invalid
3,EMP0004,Sneha Joshi,32,Female,Bangalore,Marketing,36797,5,Post Graduate,4,(987) 654-3210,sneha@,18308.0,Invalid
4,EMP0005,Vikram Singh,29,Male,Mumbai,Sales,46834,7,Diploma,8,98765,vikram@company.com,2581.0,Invalid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,EMP0166,Rahul Sharma,32,Female,Pune,IT,36797,9,Diploma,0,1234567890123,pooja gmail.com,19360.0,Invalid
155,EMP0167,Priya Patel,32,Female,Delhi,HR,36797,9,12Th,5,ABCDEFGHIJ,NaN,18680.0,Invalid
156,EMP0168,Amit Kumar,32,Male,Bangalore,Marketing,36797,9,Post Graduate,5,NaN,neha@valid.com,7229.0,Invalid
157,EMP0169,Sneha Joshi,32,Female,Hyderabad,Finance,36797,9,Graduate,5,9876543210,rahul@gmail.com,17509.0,Valid
158,EMP0170,Vikram Singh,32,Female,Pune,IT,36797,9,Post Graduate,5,8765432109,priya@yahoo.com,16147.0,Valid

In [200]:
import re
def validate_email(email):
    if pd.isnull(email):
        return 'missing'
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return 'Valid' if re.match(pattern,str(email)) else 'Invalid'

df['Valid_Email']=df['Email'].apply(validate_email)

In [201]:
df['Valid_Email'].value_counts()

Valid_Email
Valid      81
Invalid    59
missing    19
Name: count, dtype: int64

In [202]:
conditions =[
    df['Salary']<40000,(df['Salary']>40000) & (df['Salary']<80000),(df['Salary']>80000) & (df['Salary']< 120000),df['Salary']>120000
]
choices=['junior','mid level','senior','lead']
df['Salary_Grade']=np.select(conditions,choices,default='Unknown')

In [203]:
df['Salary_Grade']

0         junior
1         junior
2         junior
3         junior
4      mid level
         ...
154       junior
155       junior
156       junior
157       junior
158       junior
Name: Salary_Grade, Length: 159, dtype: object

In [204]:
df['Salary'].describe()

count      159.000000
mean     36658.157233
std       4428.222022
min          0.000000
25%      36797.000000
50%      36797.000000
75%      36797.000000
max      48776.000000
Name: Salary, dtype: float64

In [205]:
df['Total_compensation']=df['Salary']+df['Monthly_Bonus']

In [206]:
df['Total_compensation']

0      43117.0
1      51013.0
2      40576.0
3      55105.0
4      49415.0
        ...
154    56157.0
155    55477.0
156    44026.0
157    54306.0
158    52944.0
Name: Total_compensation, Length: 159, dtype: float64

In [207]:
df['Performance_category']=pd.cut(df['Performance_Score'],bins=[0,3,6,8,10],labels=['Poor','Average','Good','Excellent'])

In [209]:
df['Performance_category'].isnull().sum()

np.int64(1)

In [210]:
df['Performance_category'].value_counts()

Performance_category
Average      53
Poor         51
Good         34
Excellent    20
Name: count, dtype: int64

In [211]:
df.shape

(159, 18)

In [212]:
df.dtypes

Employee_ID               object
Employee_Name             object
Age                        int64
Gender                    object
City                      object
Department                object
Salary                     int64
Experience_Years           int64
Education                 object
Performance_Score          int64
Phone_Number              object
Email                     object
Monthly_Bonus            float64
valid_phone               object
Valid_Email               object
Salary_Grade              object
Total_compensation       float64
Performance_category    category
dtype: object

In [213]:
df['Total_compensation']=df['Total_compensation'].astype(int)
df['Monthly_Bonus']=df['Monthly_Bonus'].astype(int)

In [214]:
df.dtypes

Employee_ID               object
Employee_Name             object
Age                        int64
Gender                    object
City                      object
Department                object
Salary                     int64
Experience_Years           int64
Education                 object
Performance_Score          int64
Phone_Number              object
Email                     object
Monthly_Bonus              int64
valid_phone               object
Valid_Email               object
Salary_Grade              object
Total_compensation         int64
Performance_category    category
dtype: object

In [215]:
df.isnull().sum()

Employee_ID              0
Employee_Name            0
Age                      0
Gender                   0
City                     0
Department               0
Salary                   0
Experience_Years         0
Education                0
Performance_Score        0
Phone_Number            20
Email                   19
Monthly_Bonus            0
valid_phone              0
Valid_Email              0
Salary_Grade             0
Total_compensation       0
Performance_category     1
dtype: int64

In [216]:
df.to_csv('Cleaned_Employee_Data.csv')